version: '3'

services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000
    env_file: 
      - .env
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db


  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    env_file: 
      - .env
    restart: always
    volumes:
      - ./db_init/conf.d:/etc/mysql/conf.d
      - ./db_backend_mysql:/var/lib/mysql
      - ./db_init/table:/docker-entrypoint-initdb.d
