version: '3'

services:
  backend:
    container_name: climb-net
    build:
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file: 
      - .env
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  db:
    container_name: climber_db 
    image: postgres:15.0-alpine
    ports:
      - '5432:5432'
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata 

  redis:
    image: redis:6
    container_name: redis
    restart: unless-stopped
    volumes:
        - ./redis/data:/data
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
        - 6379
    command: redis-server /usr/local/etc/redis/redis.conf
