version: '3'

services:
  backend:
    container_name: climb-net
    build:
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file: 
      - .env
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - master #db
      - redis

  redis:
    image: redis:6
    container_name: redis
    restart: unless-stopped
    volumes:
        - ./redis/data:/data
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
        - 6379
    command: redis-server /usr/local/etc/redis/redis.conf

  # citus section
  master:
    container_name: climber_db
    image: "citusdata/citus:12.1.1"
    ports: ["5432:${POSTGRES_PORT}"]
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata 
  worker:
    image: "citusdata/citus:12.1.1"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
  manager:
    container_name: "climb-citus_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [master]
    environment: *AUTH
volumes:
  healthcheck-volume:
