{
 "title": "Dialog service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(dialog_list_req_time_s_bucket[$__rate_interval])))",
     "legendFormat": "dialog/list 95%"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(dialog_list_req_time_s_bucket[$__rate_interval])))",
     "legendFormat": "dialog/list 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(dialog_list_req_time_s_bucket[$__rate_interval])))",
     "legendFormat": "dialog/list 50%"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(dialog_create_req_time_s_bucket[$__rate_interval])))",
     "legendFormat": "dialog/create 95%"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(dialog_create_req_time_s_bucket[$__rate_interval])))",
     "legendFormat": "dialog/create 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(dialog_create_req_time_s_bucket[$__rate_interval])))",
     "legendFormat": "dialog/create 50%"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(dialog_list_req_time_s_bucket[1m]))",
     "legendFormat": "dialog/list"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(dialog_list_req_time_s_bucket[1m]))",
     "legendFormat": "dialog/create"
    }
   ]
  },
  {
   "title": "Errors 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "sum(rate(count_5xx_total[1m]))", "legendFormat": "dialog 5xx response." }
   ]
  }
 ]
}